// Generated by CoffeeScript 1.4.0
(function() {
  var argv, command, fs, optimist;

  fs = require('fs');

  optimist = require('optimist');

  argv = optimist.usage('Usage: $0 subcommand\n=== subcommands ===\n    cover').argv;

  command = argv._[0];

  if (command == null) {
    optimist.showHelp();
    process.exit(1);
  }

  if (command !== 'cover' && command !== 'report') {
    console.error("Unrecognised command: `" + command + "`. Run `" + argv['$0'] + "` for help.");
    process.exit(1);
  }

  (require("./" + command))(argv, function(err) {
    if (err) {
      console.error(err);
      process.exit(1);
    }
    return process.exit(0);
  });

}).call(this);
