// Generated by CoffeeScript 1.4.0
(function() {
  var argv, fs, optimist;

  fs = require('fs');

  optimist = require('optimist');

  argv = optimist.usage('Usage: $0 subcommand\n=== subcommands ===\n    cover').argv;

  if (!(argv._[0] != null)) {
    optimist.showHelp();
    process.exit(1);
  }

  switch (argv._[0]) {
    case 'cover':
      require('./cover')(argv, function(err) {
        if (err) {
          console.error(err);
          process.exit(1);
        }
        return process.exit(0);
      });
      break;
    case 'report':
      require('./report')(argv, function(err) {
        if (err) {
          console.error(err);
          process.exit(1);
        }
        return process.exit(0);
      });
  }

}).call(this);
