// Generated by CoffeeScript 1.10.0
(function() {
  var istanbul, key, value,
    hasProp = {}.hasOwnProperty;

  istanbul = require('istanbul');

  for (key in istanbul) {
    if (!hasProp.call(istanbul, key)) continue;
    value = istanbul[key];
    exports[key] = value;
  }

  exports.Instrumenter = require('./instrumenter');

  exports.hook = require('./hook');

  exports.version = require('../package.json').version;

}).call(this);
