// Generated by CoffeeScript 1.4.0
(function() {
  var Instrumenter, coffee, crypto, escodegen, estraverse, generateTrackerVar, istanbul,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  coffee = require('CoffeeScriptRedux');

  istanbul = require('istanbul');

  crypto = require('crypto');

  escodegen = require('escodegen');

  estraverse = require('estraverse');

  generateTrackerVar = function(filename, omitSuffix) {
    var hash, suffix;
    if (omitSuffix) {
      return '__cov_';
    }
    hash = crypto.createHash('md5');
    hash.update(filename);
    suffix = hash.digest('base64');
    suffix = suffix.replace(/\=/g, '').replace(/\+/g, '_').replace(/\//g, '$');
    return '__cov_' + suffix;
  };

  Instrumenter = (function(_super) {

    __extends(Instrumenter, _super);

    function Instrumenter(opt) {
      istanbul.Instrumenter.call(this, opt);
    }

    Instrumenter.prototype.instrumentSync = function(code, filename) {
      var codegenOptions, csast, program;
      filename = filename || Date.now() + '.js';
      this.coverState = {
        path: filename,
        s: {},
        b: {},
        f: {},
        fnMap: {},
        statementMap: {},
        branchMap: {}
      };
      this.currentState = {
        trackerVar: generateTrackerVar(filename, this.omitTrackerSuffix),
        func: 0,
        branch: 0,
        variable: 0,
        statement: 0
      };
      if (typeof code !== 'string') {
        throw new Error('Code must be string');
      }
      if (code[0] === '#') {
        code = '//' + code;
      }
      csast = coffee.parse(code, {
        optimise: false
      });
      program = coffee.compile(csast, {
        bare: true
      });
      this.attachLocation(program);
      this.walker.startWalk(program);
      codegenOptions = this.opts.codeGenerationOptions || {
        format: {
          compact: !this.opts.noCompact
        }
      };
      return this.getPreamble(code) + '\n' + escodegen.generate(program, codegenOptions) + '\n';
    };

    Instrumenter.prototype.attachLocation = function(tree) {
      return estraverse.traverse(tree, {
        enter: function(node, parent) {
          var lines;
          if ((node.column != null) && (node.line != null) && (node.raw != null)) {
            node.loc = {
              start: {
                line: node.line,
                column: node.column
              },
              end: {
                line: node.line,
                column: node.column + node.raw.length
              }
            };
            lines = node.raw.split(/(?:\n|\r|[\r\n])/);
            if (lines.length !== 0 && lines.length !== 1) {
              node.loc.end.line += lines.lines;
              return node.loc.end.column = lines[lines.length - 1].length;
            }
          }
        }
      });
    };

    return Instrumenter;

  })(istanbul.Instrumenter);

  module.exports = Instrumenter;

}).call(this);
